version: "3:8"
services:
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - auth
    networks:
      - common

  auth:
    build:
      dockerfile: Dockerfile
      context: ./auth
    container_name: auth
    restart: always
    volumes:
      - .:/app
      - /app/auth/node_modules
    depends_on:
      - auth_db
    networks:
      - common

  auth_db:
    image: mysql:latest
    container_name: auth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - common

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - auth_db
    networks:
      - common

  notification:
    build:
      dockerfile: Dockerfile
      context: ./notification
    container_name: notification
    restart: always
    volumes:
      - .:/app
      - /app/notification/node_modules
    networks:
      - common

volumes:
  auth_data:
    driver: local

networks:
  common:
